# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/scohen/Documents/Drone/FlightController

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/scohen/Documents/Drone/FlightController

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/scohen/Documents/Drone/FlightController/CMakeFiles /home/scohen/Documents/Drone/FlightController/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/scohen/Documents/Drone/FlightController/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FlightController

# Build rule for target.
FlightController: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FlightController
.PHONY : FlightController

# fast build rule for target.
FlightController/fast:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/build
.PHONY : FlightController/fast

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) -f CMakeFiles/flash.dir/build.make CMakeFiles/flash.dir/build
.PHONY : flash/fast

#=============================================================================
# Target rules for targets named FlightController.hex

# Build rule for target.
FlightController.hex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FlightController.hex
.PHONY : FlightController.hex

# fast build rule for target.
FlightController.hex/fast:
	$(MAKE) -f CMakeFiles/FlightController.hex.dir/build.make CMakeFiles/FlightController.hex.dir/build
.PHONY : FlightController.hex/fast

#=============================================================================
# Target rules for targets named FlightController.bin

# Build rule for target.
FlightController.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FlightController.bin
.PHONY : FlightController.bin

# fast build rule for target.
FlightController.bin/fast:
	$(MAKE) -f CMakeFiles/FlightController.bin.dir/build.make CMakeFiles/FlightController.bin.dir/build
.PHONY : FlightController.bin/fast

Src/imu.obj: Src/imu.cpp.obj

.PHONY : Src/imu.obj

# target to build an object file
Src/imu.cpp.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/imu.cpp.obj
.PHONY : Src/imu.cpp.obj

Src/imu.i: Src/imu.cpp.i

.PHONY : Src/imu.i

# target to preprocess a source file
Src/imu.cpp.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/imu.cpp.i
.PHONY : Src/imu.cpp.i

Src/imu.s: Src/imu.cpp.s

.PHONY : Src/imu.s

# target to generate assembly for a file
Src/imu.cpp.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/imu.cpp.s
.PHONY : Src/imu.cpp.s

Src/main.obj: Src/main.cpp.obj

.PHONY : Src/main.obj

# target to build an object file
Src/main.cpp.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/main.cpp.obj
.PHONY : Src/main.cpp.obj

Src/main.i: Src/main.cpp.i

.PHONY : Src/main.i

# target to preprocess a source file
Src/main.cpp.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/main.cpp.i
.PHONY : Src/main.cpp.i

Src/main.s: Src/main.cpp.s

.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.cpp.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/main.cpp.s
.PHONY : Src/main.cpp.s

Src/stm32f3xx_hal_msp.obj: Src/stm32f3xx_hal_msp.c.obj

.PHONY : Src/stm32f3xx_hal_msp.obj

# target to build an object file
Src/stm32f3xx_hal_msp.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/stm32f3xx_hal_msp.c.obj
.PHONY : Src/stm32f3xx_hal_msp.c.obj

Src/stm32f3xx_hal_msp.i: Src/stm32f3xx_hal_msp.c.i

.PHONY : Src/stm32f3xx_hal_msp.i

# target to preprocess a source file
Src/stm32f3xx_hal_msp.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/stm32f3xx_hal_msp.c.i
.PHONY : Src/stm32f3xx_hal_msp.c.i

Src/stm32f3xx_hal_msp.s: Src/stm32f3xx_hal_msp.c.s

.PHONY : Src/stm32f3xx_hal_msp.s

# target to generate assembly for a file
Src/stm32f3xx_hal_msp.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/stm32f3xx_hal_msp.c.s
.PHONY : Src/stm32f3xx_hal_msp.c.s

Src/stm32f3xx_it.obj: Src/stm32f3xx_it.c.obj

.PHONY : Src/stm32f3xx_it.obj

# target to build an object file
Src/stm32f3xx_it.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/stm32f3xx_it.c.obj
.PHONY : Src/stm32f3xx_it.c.obj

Src/stm32f3xx_it.i: Src/stm32f3xx_it.c.i

.PHONY : Src/stm32f3xx_it.i

# target to preprocess a source file
Src/stm32f3xx_it.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/stm32f3xx_it.c.i
.PHONY : Src/stm32f3xx_it.c.i

Src/stm32f3xx_it.s: Src/stm32f3xx_it.c.s

.PHONY : Src/stm32f3xx_it.s

# target to generate assembly for a file
Src/stm32f3xx_it.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/stm32f3xx_it.c.s
.PHONY : Src/stm32f3xx_it.c.s

Src/usb_device.obj: Src/usb_device.c.obj

.PHONY : Src/usb_device.obj

# target to build an object file
Src/usb_device.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usb_device.c.obj
.PHONY : Src/usb_device.c.obj

Src/usb_device.i: Src/usb_device.c.i

.PHONY : Src/usb_device.i

# target to preprocess a source file
Src/usb_device.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usb_device.c.i
.PHONY : Src/usb_device.c.i

Src/usb_device.s: Src/usb_device.c.s

.PHONY : Src/usb_device.s

# target to generate assembly for a file
Src/usb_device.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usb_device.c.s
.PHONY : Src/usb_device.c.s

Src/usbd_cdc_if.obj: Src/usbd_cdc_if.c.obj

.PHONY : Src/usbd_cdc_if.obj

# target to build an object file
Src/usbd_cdc_if.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usbd_cdc_if.c.obj
.PHONY : Src/usbd_cdc_if.c.obj

Src/usbd_cdc_if.i: Src/usbd_cdc_if.c.i

.PHONY : Src/usbd_cdc_if.i

# target to preprocess a source file
Src/usbd_cdc_if.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usbd_cdc_if.c.i
.PHONY : Src/usbd_cdc_if.c.i

Src/usbd_cdc_if.s: Src/usbd_cdc_if.c.s

.PHONY : Src/usbd_cdc_if.s

# target to generate assembly for a file
Src/usbd_cdc_if.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usbd_cdc_if.c.s
.PHONY : Src/usbd_cdc_if.c.s

Src/usbd_conf.obj: Src/usbd_conf.c.obj

.PHONY : Src/usbd_conf.obj

# target to build an object file
Src/usbd_conf.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usbd_conf.c.obj
.PHONY : Src/usbd_conf.c.obj

Src/usbd_conf.i: Src/usbd_conf.c.i

.PHONY : Src/usbd_conf.i

# target to preprocess a source file
Src/usbd_conf.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usbd_conf.c.i
.PHONY : Src/usbd_conf.c.i

Src/usbd_conf.s: Src/usbd_conf.c.s

.PHONY : Src/usbd_conf.s

# target to generate assembly for a file
Src/usbd_conf.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usbd_conf.c.s
.PHONY : Src/usbd_conf.c.s

Src/usbd_desc.obj: Src/usbd_desc.c.obj

.PHONY : Src/usbd_desc.obj

# target to build an object file
Src/usbd_desc.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usbd_desc.c.obj
.PHONY : Src/usbd_desc.c.obj

Src/usbd_desc.i: Src/usbd_desc.c.i

.PHONY : Src/usbd_desc.i

# target to preprocess a source file
Src/usbd_desc.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usbd_desc.c.i
.PHONY : Src/usbd_desc.c.i

Src/usbd_desc.s: Src/usbd_desc.c.s

.PHONY : Src/usbd_desc.s

# target to generate assembly for a file
Src/usbd_desc.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/Src/usbd_desc.c.s
.PHONY : Src/usbd_desc.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc.s.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc.s.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc.s.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc.s.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.s

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.obj: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.obj

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.obj

# target to build an object file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.obj:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.obj
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.obj

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.i: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.i

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.i

# target to preprocess a source file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.i:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.i
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.i

home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.s: home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.s

.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.s

# target to generate assembly for a file
home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.s:
	$(MAKE) -f CMakeFiles/FlightController.dir/build.make CMakeFiles/FlightController.dir/home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.s
.PHONY : home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... FlightController"
	@echo "... flash"
	@echo "... edit_cache"
	@echo "... FlightController.hex"
	@echo "... FlightController.bin"
	@echo "... Src/imu.obj"
	@echo "... Src/imu.i"
	@echo "... Src/imu.s"
	@echo "... Src/main.obj"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
	@echo "... Src/stm32f3xx_hal_msp.obj"
	@echo "... Src/stm32f3xx_hal_msp.i"
	@echo "... Src/stm32f3xx_hal_msp.s"
	@echo "... Src/stm32f3xx_it.obj"
	@echo "... Src/stm32f3xx_it.i"
	@echo "... Src/stm32f3xx_it.s"
	@echo "... Src/usb_device.obj"
	@echo "... Src/usb_device.i"
	@echo "... Src/usb_device.s"
	@echo "... Src/usbd_cdc_if.obj"
	@echo "... Src/usbd_cdc_if.i"
	@echo "... Src/usbd_cdc_if.s"
	@echo "... Src/usbd_conf.obj"
	@echo "... Src/usbd_conf.i"
	@echo "... Src/usbd_conf.s"
	@echo "... Src/usbd_desc.obj"
	@echo "... Src/usbd_desc.i"
	@echo "... Src/usbd_desc.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/l3gd20/l3gd20.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/Components/lsm303dlhc/lsm303dlhc.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_accelerometer.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/BSP/STM32F3-Discovery/stm32f3_discovery_gyroscope.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.s"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.obj"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.i"
	@echo "... home/scohen/STM32Cube/Repository/STM32Cube_FW_F3_V1.10.0/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

